name: 'Slova Site Generator'
description: 'Generate static html files'

inputs:
  title:
    description: 'Title of the generated HTML page'
    required: true
  content:
    description: 'Content of the generated HTML page'
    required: true

outputs:
  html_path:
    description: 'Path to the generated HTML file'

runs:
  using: 'node20'
  main: 'index.js'