name: 'Slova Site Generator'
description: 'Generate static html files'

inputs:
  context:
    description: 'Path to yml file with context data'
    required: true
  path:
    description: 'Destination path to generate html'
    required: true
  pages:
    description: 'Path to user .md pages'
    required: true
  theme:
    description: 'Path to theme template directory'
    required: true

outputs:
  html_path:
    description: 'Path to the generated HTML files'

runs:
  using: 'node20'
  main: 'dist/index.js'